"""Agents router – spawn, monitor, and manage AI agents."""
from typing import Any, Dict, List

from fastapi import APIRouter, HTTPException

from app.models.schemas import (
    AgentSearchKBRequest,
    AgentSearchKBResponse,
    AgentSearchKBResult,
    AgentStatusResponse,
    ArtifactResponse,
    SpawnAgentRequest,
    SpawnSubAgentRequest,
    SpawnSubAgentResponse,
)
from app.services.agent_orchestrator import get_agent_orchestrator
from app.utils.constants import MAX_SUB_AGENT_DEPTH

router = APIRouter()


@router.post("/agents/spawn", tags=["agents"])
async def spawn_agent(body: SpawnAgentRequest) -> Dict[str, Any]:
    """Spawn a new AI agent with a task definition."""
    orchestrator = get_agent_orchestrator()
    try:
        agent_id = await orchestrator.spawn_agent(
            agent_type=body.agent_type,
            task=body.task,
            workspace=body.workspace,
            skill_ids=body.skill_ids,
        )
        return {
            "agent_id": agent_id,
            "agent_type": body.agent_type,
            "status": "pending",
            "message": "Agent spawned successfully",
        }
    except RuntimeError as exc:
        raise HTTPException(status_code=429, detail=str(exc))


@router.get("/agents", tags=["agents"])
async def list_agents() -> Dict[str, Any]:
    """List all active agents with their current status."""
    orchestrator = get_agent_orchestrator()
    agents = orchestrator.list_agents()
    return {"agents": agents, "count": len(agents)}


@router.get("/agents/{agent_id}/status", response_model=AgentStatusResponse, tags=["agents"])
async def get_agent_status(agent_id: str) -> Dict[str, Any]:
    """Get the current status and progress of an agent."""
    orchestrator = get_agent_orchestrator()
    agent = orchestrator.get_agent(agent_id)
    if not agent:
        raise HTTPException(status_code=404, detail=f"Agent {agent_id} not found")
    return agent


@router.get("/agents/{agent_id}/artifacts", tags=["agents"])
async def get_agent_artifacts(agent_id: str) -> Dict[str, Any]:
    """Get all artifacts generated by an agent, with preview data."""
    orchestrator = get_agent_orchestrator()
    if not orchestrator.get_agent(agent_id):
        raise HTTPException(status_code=404, detail=f"Agent {agent_id} not found")
    artifacts = orchestrator.get_agent_artifacts_with_preview(agent_id)
    return {"agent_id": agent_id, "artifacts": artifacts}


@router.get("/agents/artifacts/{artifact_id}", tags=["agents"])
async def get_artifact(artifact_id: str) -> Dict[str, Any]:
    """Retrieve a specific artifact by ID."""
    orchestrator = get_agent_orchestrator()
    artifact = orchestrator.get_artifact(artifact_id)
    if not artifact:
        raise HTTPException(status_code=404, detail=f"Artifact {artifact_id} not found")
    return artifact


@router.post("/agents/{agent_id}/search-kb", tags=["agents"])
async def agent_search_kb(agent_id: str, query: str, top_k: int = 3) -> Dict[str, Any]:
    """Agent searches the knowledge base during its workflow."""
    orchestrator = get_agent_orchestrator()
    if not orchestrator.get_agent(agent_id):
        raise HTTPException(status_code=404, detail=f"Agent {agent_id} not found")

    results = await orchestrator.search_knowledge_base(query, top_k)
    return {"agent_id": agent_id, "query": query, "results": results}


@router.post("/agents/{agent_id}/spawn-sub-agent", tags=["agents"])
async def spawn_sub_agent(
    agent_id: str,
    task: str = "",
    agent_type: str = "general",
) -> Dict[str, Any]:
    """Spawn a sub-agent from a parent agent."""
    orchestrator = get_agent_orchestrator()
    if not orchestrator.get_agent(agent_id):
        raise HTTPException(status_code=404, detail=f"Agent {agent_id} not found")

    if not task:
        raise HTTPException(status_code=400, detail="Task description is required")

    sub_id = await orchestrator.spawn_sub_agent(agent_id, task, agent_type)
    if not sub_id:
        raise HTTPException(
            status_code=400,
            detail="Cannot spawn sub-agent: depth limit reached or parent not found",
        )

    return {
        "parent_agent_id": agent_id,
        "sub_agent_id": sub_id,
        "agent_type": agent_type,
        "status": "pending",
    }


@router.post("/agents/{agent_id}/interrupt", tags=["agents"])
async def interrupt_agent(agent_id: str) -> Dict[str, Any]:
    """Gracefully stop a running agent."""
    orchestrator = get_agent_orchestrator()
    success = await orchestrator.interrupt_agent(agent_id)
    if not success:
        raise HTTPException(
            status_code=400,
            detail=f"Agent {agent_id} is not running or does not exist",
        )
    return {"agent_id": agent_id, "status": "interrupted"}


@router.delete("/agents/{agent_id}", tags=["agents"])
async def delete_agent(agent_id: str) -> Dict[str, Any]:
    """Terminate and remove an agent."""
    orchestrator = get_agent_orchestrator()
    success = await orchestrator.delete_agent(agent_id)
    if not success:
        raise HTTPException(status_code=404, detail=f"Agent {agent_id} not found")
    return {"agent_id": agent_id, "deleted": True}


@router.post("/agents/cleanup", tags=["agents"])
async def cleanup_agents() -> Dict[str, Any]:
    """Remove all completed/failed agents."""
    orchestrator = get_agent_orchestrator()
    count = orchestrator.cleanup_finished()
    return {"removed": count}


@router.post("/agents/search-kb", response_model=AgentSearchKBResponse, tags=["agents"])
async def agent_search_kb(body: AgentSearchKBRequest) -> AgentSearchKBResponse:
    """
    Search the knowledge base on behalf of an agent.

    - query length: 1–500 characters
    - top_k: 1–20 results (default 3)
    """
    from app.services.embeddings_service import get_embeddings_service
    from app.services.vector_store_service import get_vector_store_service
    from app.utils.constants import MIN_KB_SEARCH_SCORE

    embeddings_svc = get_embeddings_service()
    vector_store = get_vector_store_service()

    query_embedding = await embeddings_svc.generate_embedding(body.query)
    if not query_embedding:
        raise HTTPException(status_code=500, detail="Failed to generate query embedding")

    raw = vector_store.search(query_embedding=query_embedding, top_k=body.top_k)

    results = [
        AgentSearchKBResult(
            text=doc,
            file_name=meta.get("file_name", ""),
            file_path=meta.get("file_path", ""),
            score=round(1 - dist, 4),
        )
        for doc, meta, dist in zip(raw["documents"], raw["metadatas"], raw["distances"])
        if (1 - dist) >= MIN_KB_SEARCH_SCORE
    ]

    return AgentSearchKBResponse(results=results, query=body.query, count=len(results))


@router.post("/agents/spawn-sub", response_model=SpawnSubAgentResponse, tags=["agents"])
async def spawn_sub_agent(body: SpawnSubAgentRequest) -> SpawnSubAgentResponse:
    """
    Spawn a sub-agent from within an agent task.

    Enforces MAX_SUB_AGENT_DEPTH to prevent runaway agent trees.
    - task length: 1–2000 characters
    - agent_type: general | code | research | testing | devops
    """
    orchestrator = get_agent_orchestrator()

    active = [
        a for a in orchestrator.list_agents()
        if a["status"] in ("pending", "running")
    ]
    if len(active) >= MAX_SUB_AGENT_DEPTH:
        raise HTTPException(
            status_code=429,
            detail=(
                f"Sub-agent depth limit ({MAX_SUB_AGENT_DEPTH}) reached. "
                "Wait for active sub-agents to complete before spawning more."
            ),
        )

    try:
        agent_id = await orchestrator.spawn_agent(
            agent_type=body.agent_type,
            task={"goal": body.task},
        )
    except RuntimeError as exc:
        raise HTTPException(status_code=429, detail=str(exc))

    return SpawnSubAgentResponse(
        agent_id=agent_id,
        agent_type=body.agent_type,
        status="pending",
        message="Sub-agent spawned successfully",
    )
