"""ReportGeneratorService – generate PDF, HTML reports, and HTML slide decks."""
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from app.models.document_analysis_models import DocumentAnalysisResult

logger = logging.getLogger(__name__)


def generate_pdf(markdown_text: str, output_path: str, title: str) -> str:
    """Convert Markdown to PDF via HTML+weasyprint. Falls back to .html if weasyprint unavailable."""
    import markdown as md

    html_body = md.markdown(
        markdown_text,
        extensions=["tables", "fenced_code", "nl2br"],
    )

    full_html = _wrap_html(html_body, title)

    try:
        from weasyprint import HTML
        HTML(string=full_html).write_pdf(output_path)
        logger.info("PDF generated: %s", output_path)
        return output_path
    except ImportError:
        logger.warning("weasyprint not installed — saving as HTML instead of PDF")
        fallback_path = output_path.replace(".pdf", ".html")
        Path(fallback_path).write_text(full_html, encoding="utf-8")
        return fallback_path
    except Exception as exc:
        logger.warning("weasyprint failed (%s) — saving as HTML fallback", exc)
        fallback_path = output_path.replace(".pdf", ".html")
        Path(fallback_path).write_text(full_html, encoding="utf-8")
        return fallback_path


def generate_html_report(result: DocumentAnalysisResult, output_path: str, title: str) -> str:
    """Build a structured HTML report from DocumentAnalysisResult."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Per-document sections
    doc_sections = ""
    for i, doc in enumerate(result.documents, 1):
        key_points_html = ""
        if doc.key_points:
            items = "".join(f"<li>{_esc(kp)}</li>" for kp in doc.key_points)
            key_points_html = f"<h4>Key Points</h4><ul>{items}</ul>"

        risks_html = ""
        if doc.risks_or_gaps:
            items = "".join(f"<li>{_esc(r)}</li>" for r in doc.risks_or_gaps)
            risks_html = f"<h4>Risks / Gaps</h4><ul class='risks'>{items}</ul>"

        metrics_html = ""
        if doc.metrics:
            rows = "".join(
                f"<tr><td>{_esc(k)}</td><td>{_esc(v)}</td></tr>"
                for k, v in doc.metrics.items()
            )
            metrics_html = f"<h4>Metrics</h4><table><thead><tr><th>Metric</th><th>Value</th></tr></thead><tbody>{rows}</tbody></table>"

        doc_sections += f"""
        <div class="doc-card">
            <h3>{i}. {_esc(doc.title)}</h3>
            <p class="file-path"><code>{_esc(doc.file_path)}</code></p>
            <p>{_esc(doc.summary)}</p>
            {key_points_html}
            {risks_html}
            {metrics_html}
        </div>
        """

    # Recommendations
    recs_html = ""
    if result.recommendations:
        items = "".join(f"<li>{_esc(r)}</li>" for i, r in enumerate(result.recommendations, 1))
        recs_html = f"<h2>Recommendations</h2><ol class='recommendations'>{items}</ol>"

    body = f"""
    <header>
        <h1>{_esc(title)}</h1>
        <div class="meta">
            <span>Generated: {now}</span>
            <span>Documents: {len(result.documents)}</span>
        </div>
        <p class="task"><strong>Task:</strong> {_esc(result.task_description)}</p>
    </header>

    <section class="summary">
        <h2>Executive Summary</h2>
        <p>{_esc(result.overall_summary)}</p>
    </section>

    <section class="documents">
        <h2>Per-Document Analysis</h2>
        {doc_sections}
    </section>

    {recs_html}

    <footer>
        <p>Generated by AI Home Hub</p>
    </footer>
    """

    full_html = _wrap_report_html(body, title)
    Path(output_path).write_text(full_html, encoding="utf-8")
    logger.info("HTML report generated: %s", output_path)
    return output_path


def generate_slides_html(result: DocumentAnalysisResult, output_path: str, title: str) -> str:
    """Generate a self-contained HTML slide deck with pure CSS navigation."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    slides = []

    # Slide 1: Title
    slides.append(f"""
    <div class="slide">
        <h1>{_esc(title)}</h1>
        <p class="subtitle">{_esc(result.task_description)}</p>
        <p class="date">{now}</p>
        <p class="doc-count">{len(result.documents)} document(s) analyzed</p>
    </div>
    """)

    # Slide 2: Executive Summary
    slides.append(f"""
    <div class="slide">
        <h2>Executive Summary</h2>
        <p>{_esc(result.overall_summary)}</p>
    </div>
    """)

    # Slides 3..N: One per document
    for i, doc in enumerate(result.documents, 1):
        points = ""
        if doc.key_points:
            items = "".join(f"<li>{_esc(kp)}</li>" for kp in doc.key_points[:3])
            points = f"<ul>{items}</ul>"

        risks = ""
        if doc.risks_or_gaps:
            items = "".join(f"<li>{_esc(r)}</li>" for r in doc.risks_or_gaps[:2])
            risks = f"<h3>Risks</h3><ul class='risks'>{items}</ul>"

        slides.append(f"""
        <div class="slide">
            <h2>{i}. {_esc(doc.title)}</h2>
            <p>{_esc(doc.summary[:300])}</p>
            {points}
            {risks}
        </div>
        """)

    # Last slide: Recommendations
    if result.recommendations:
        items = "".join(f"<li>{_esc(r)}</li>" for r in result.recommendations)
        slides.append(f"""
        <div class="slide">
            <h2>Recommendations</h2>
            <ol>{items}</ol>
        </div>
        """)

    slides_html = "\n".join(slides)
    total_slides = len(slides)

    full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_esc(title)} – Slides</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
    font-family: system-ui, -apple-system, sans-serif;
    background: #1a1a2e;
    color: #e2e8f0;
    overflow: hidden;
    height: 100vh;
}}
.slide {{
    display: none;
    width: 100vw;
    height: 100vh;
    padding: 8vh 10vw;
    flex-direction: column;
    justify-content: center;
}}
.slide.active {{ display: flex; }}
.slide h1 {{ font-size: 3rem; margin-bottom: 1rem; color: #60a5fa; }}
.slide h2 {{ font-size: 2.2rem; margin-bottom: 1.5rem; color: #60a5fa; }}
.slide h3 {{ font-size: 1.4rem; margin-top: 1.5rem; margin-bottom: 0.5rem; color: #93c5fd; }}
.slide p {{ font-size: 1.3rem; line-height: 1.6; margin-bottom: 0.75rem; }}
.slide .subtitle {{ font-size: 1.5rem; color: #94a3b8; }}
.slide .date {{ font-size: 1.1rem; color: #64748b; margin-top: 1rem; }}
.slide .doc-count {{ font-size: 1rem; color: #64748b; }}
.slide ul, .slide ol {{ margin: 1rem 0 1rem 2rem; font-size: 1.2rem; line-height: 1.8; }}
.slide li {{ margin-bottom: 0.5rem; }}
.slide .risks li {{ color: #fbbf24; }}
.controls {{
    position: fixed;
    bottom: 2rem;
    right: 2rem;
    display: flex;
    gap: 0.75rem;
    align-items: center;
    z-index: 100;
}}
.controls button {{
    background: #334155;
    color: #e2e8f0;
    border: 1px solid #475569;
    padding: 0.5rem 1.2rem;
    border-radius: 6px;
    cursor: pointer;
    font-size: 1rem;
}}
.controls button:hover {{ background: #475569; }}
.controls .counter {{ color: #64748b; font-size: 0.9rem; }}
</style>
</head>
<body>
{slides_html}

<div class="controls">
    <button onclick="prevSlide()">&larr; Prev</button>
    <span class="counter" id="counter">1 / {total_slides}</span>
    <button onclick="nextSlide()">Next &rarr;</button>
</div>

<script>
let current = 0;
const slides = document.querySelectorAll('.slide');
const counter = document.getElementById('counter');
const total = slides.length;

function showSlide(n) {{
    slides.forEach(s => s.classList.remove('active'));
    current = ((n % total) + total) % total;
    slides[current].classList.add('active');
    counter.textContent = (current + 1) + ' / ' + total;
}}

function nextSlide() {{ showSlide(current + 1); }}
function prevSlide() {{ showSlide(current - 1); }}

document.addEventListener('keydown', e => {{
    if (e.key === 'ArrowRight' || e.key === ' ') nextSlide();
    if (e.key === 'ArrowLeft') prevSlide();
}});

showSlide(0);
</script>
</body>
</html>"""

    Path(output_path).write_text(full_html, encoding="utf-8")
    logger.info("Slides HTML generated: %s", output_path)
    return output_path


# ── Helpers ──────────────────────────────────────────────────


def _esc(text: str) -> str:
    """Escape HTML special characters."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _wrap_html(body: str, title: str) -> str:
    """Wrap markdown-generated HTML in a basic print-friendly template."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{_esc(title)}</title>
<style>
body {{
    font-family: system-ui, -apple-system, sans-serif;
    max-width: 800px;
    margin: 2rem auto;
    padding: 0 1.5rem;
    line-height: 1.6;
    color: #1a1a1a;
    background: #fff;
}}
h1 {{ font-size: 1.8rem; margin-bottom: 1rem; border-bottom: 2px solid #3b82f6; padding-bottom: 0.5rem; }}
h2 {{ font-size: 1.4rem; margin-top: 2rem; margin-bottom: 0.75rem; color: #1e40af; }}
h3 {{ font-size: 1.2rem; margin-top: 1.5rem; }}
table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
th, td {{ border: 1px solid #d1d5db; padding: 0.5rem 0.75rem; text-align: left; }}
th {{ background: #f3f4f6; }}
code {{ background: #f3f4f6; padding: 0.15rem 0.3rem; border-radius: 3px; font-size: 0.9em; }}
pre {{ background: #f3f4f6; padding: 1rem; border-radius: 6px; overflow-x: auto; }}
ul, ol {{ margin: 0.5rem 0 0.5rem 1.5rem; }}
@media print {{
    body {{ max-width: 100%; margin: 0; padding: 1cm; }}
}}
</style>
</head>
<body>
{body}
</body>
</html>"""


def _wrap_report_html(body: str, title: str) -> str:
    """Wrap a structured report in a styled HTML template."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{_esc(title)}</title>
<style>
body {{
    font-family: system-ui, -apple-system, sans-serif;
    max-width: 900px;
    margin: 0 auto;
    padding: 2rem 1.5rem;
    line-height: 1.6;
    color: #1a1a1a;
    background: #fff;
}}
header {{
    border-bottom: 3px solid #3b82f6;
    padding-bottom: 1.5rem;
    margin-bottom: 2rem;
}}
header h1 {{ font-size: 2rem; color: #1e3a5f; margin-bottom: 0.5rem; }}
header .meta {{
    display: flex;
    gap: 2rem;
    color: #64748b;
    font-size: 0.9rem;
    margin-bottom: 0.75rem;
}}
header .task {{ color: #334155; font-size: 1rem; }}
h2 {{ font-size: 1.5rem; color: #1e40af; margin-top: 2rem; margin-bottom: 1rem; border-bottom: 1px solid #e2e8f0; padding-bottom: 0.5rem; }}
h3 {{ font-size: 1.2rem; color: #1e3a5f; margin-bottom: 0.5rem; }}
h4 {{ font-size: 1rem; color: #475569; margin-top: 1rem; margin-bottom: 0.5rem; }}
.doc-card {{
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    padding: 1.25rem;
    margin-bottom: 1.5rem;
}}
.doc-card .file-path {{ color: #64748b; font-size: 0.85rem; }}
table {{ border-collapse: collapse; width: 100%; margin: 0.75rem 0; }}
th, td {{ border: 1px solid #d1d5db; padding: 0.5rem 0.75rem; text-align: left; }}
th {{ background: #f1f5f9; font-weight: 600; }}
ul, ol {{ margin: 0.5rem 0 0.5rem 1.5rem; }}
li {{ margin-bottom: 0.3rem; }}
.risks li {{ color: #b45309; }}
.recommendations li {{ margin-bottom: 0.5rem; }}
footer {{
    margin-top: 3rem;
    padding-top: 1rem;
    border-top: 1px solid #e2e8f0;
    color: #94a3b8;
    font-size: 0.85rem;
    text-align: center;
}}
code {{ background: #f1f5f9; padding: 0.15rem 0.3rem; border-radius: 3px; font-size: 0.9em; }}
@media print {{
    body {{ max-width: 100%; margin: 0; padding: 1cm; }}
    .doc-card {{ break-inside: avoid; }}
}}
</style>
</head>
<body>
{body}
</body>
</html>"""
