"""Resident Agent package – re-exports for backwards compatibility.

All existing ``from app.services.resident_agent import …`` statements
continue to work unchanged.
"""

from app.services.resident_agent.core import (  # noqa: F401
    ALLOWED_ACTIONS,
    ACTION_COOLDOWNS,
    ACTION_TIERS,
    CONSECUTIVE_ERROR_THRESHOLD,
    CycleRecord,
    HEARTBEAT_INTERVAL_S,
    HEARTBEAT_MISS_THRESHOLD_S,
    KB_DOCS_ALERT_THRESHOLD,
    KB_REINDEX_COOLDOWN_S,
    LogEntry,
    MAX_CYCLE_HISTORY,
    MAX_LOG_ENTRIES,
    MAX_REFLECTIONS_HISTORY,
    MAX_SUGGESTIONS_HISTORY,
    METRICS_CACHE_TTL_S,
    MISSION_TICK_INTERVAL,
    MODE_ALLOWED_ACTIONS,
    MissionProposal,
    QUEUE_DEPTH_ALERT_THRESHOLD,
    ResidentAgent,
    ResidentAgentState,
    THOUGHT_TICK_INTERVAL,
    WS_EVENT_RESIDENT_ACTION,
    WS_EVENT_RESIDENT_SUGGESTION,
    WS_EVENT_RESIDENT_TICK,
    AgentSettings,
    ActionBlockedError,
    get_resident_agent,
)

__all__ = [
    "ALLOWED_ACTIONS",
    "ACTION_COOLDOWNS",
    "ACTION_TIERS",
    "CONSECUTIVE_ERROR_THRESHOLD",
    "CycleRecord",
    "HEARTBEAT_INTERVAL_S",
    "HEARTBEAT_MISS_THRESHOLD_S",
    "KB_DOCS_ALERT_THRESHOLD",
    "KB_REINDEX_COOLDOWN_S",
    "LogEntry",
    "MAX_CYCLE_HISTORY",
    "MAX_LOG_ENTRIES",
    "MAX_REFLECTIONS_HISTORY",
    "MAX_SUGGESTIONS_HISTORY",
    "METRICS_CACHE_TTL_S",
    "MISSION_TICK_INTERVAL",
    "MODE_ALLOWED_ACTIONS",
    "MissionProposal",
    "QUEUE_DEPTH_ALERT_THRESHOLD",
    "ResidentAgent",
    "ResidentAgentState",
    "THOUGHT_TICK_INTERVAL",
    "WS_EVENT_RESIDENT_ACTION",
    "WS_EVENT_RESIDENT_SUGGESTION",
    "WS_EVENT_RESIDENT_TICK",
    "AgentSettings",
    "ActionBlockedError",
    "get_resident_agent",
]
